### ISSUE TITLE
when would the code be released?

### ISSUE THREAD

**Issue by linziqu** [zj-dong/AG3D#1]

**Comment by zj-dong** [comment]
Thanks for your interests! Our paper is currently accepted by ICCV and we will release our code in the following month.

**Comment by ZunDuJiaDu** [comment]
Hi there, thank you for your great work. Any updates of the code release?

**Comment by zj-dong** [comment]
Yes, the inference code will be released in one week and the training code will also be released soon.

**Comment by zhangxujinsh** [comment]
Dr. Dong  @zj-dong 
   Thanks for your solid work. Looking forward to learning the training code !
