### ISSUE TITLE
Texture?

### ISSUE THREAD

**Issue by MilesTheProwler** [zj-dong/AG3D#2]
Hi, thank you for sharing your work. I just want to know about does you model can do body texture? 

I also want to know how did you animate these mesh model? Did you use auto rigged function ? Can we output 3D mesh obj ?

**Comment by zj-dong** [comment]
Hi, the body texture is rendered by volumetric rendering (similar to NeRF or VolSDF). Yes, the mesh is obtained via marching Cuba and can be animated by a skinning model. Please see more details in our paper.
